version: '3.8'

services:
  db:
    image: mysql:8.3
    restart: always
    ports:
      - "52000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lemp
    volumes:
      - lemp-db-volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lemp-network
  backend:
    build:
      context: ./php/
    restart: always
    depends_on:
      - db
    volumes:
      - lemp-backend-volume:/app/
    networks:
      - lemp-network
  webserver:
    image: nginx:1.21.6
    restart: always
    ports:
      - "4002:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - lemp-backend-volume:/app/
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge

volumes:
  lemp-db-volume:
  lemp-backend-volume:
